services:
  prestayar_localizer_controller_localizerspecificprice:
    class: PrestaYar\Localizer\Controller\LocalizerSpecificPriceController
    decorates: PrestaShopBundle\Controller\Admin\SpecificPriceController
    arguments: ['@prestayar_localizer_controller_localizerspecificprice.inner']    